# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /user/vigiert/E4_hmd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /user/vigiert/E4_hmd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /user/vigiert/E4_hmd/CMakeFiles /user/vigiert/E4_hmd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /user/vigiert/E4_hmd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openglexample

# Build rule for target.
openglexample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openglexample
.PHONY : openglexample

# fast build rule for target.
openglexample/fast:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/build
.PHONY : openglexample/fast

src/Debug.o: src/Debug.cpp.o

.PHONY : src/Debug.o

# target to build an object file
src/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Debug.cpp.o
.PHONY : src/Debug.cpp.o

src/Debug.i: src/Debug.cpp.i

.PHONY : src/Debug.i

# target to preprocess a source file
src/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Debug.cpp.i
.PHONY : src/Debug.cpp.i

src/Debug.s: src/Debug.cpp.s

.PHONY : src/Debug.s

# target to generate assembly for a file
src/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Debug.cpp.s
.PHONY : src/Debug.cpp.s

src/GLFWContext.o: src/GLFWContext.cpp.o

.PHONY : src/GLFWContext.o

# target to build an object file
src/GLFWContext.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/GLFWContext.cpp.o
.PHONY : src/GLFWContext.cpp.o

src/GLFWContext.i: src/GLFWContext.cpp.i

.PHONY : src/GLFWContext.i

# target to preprocess a source file
src/GLFWContext.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/GLFWContext.cpp.i
.PHONY : src/GLFWContext.cpp.i

src/GLFWContext.s: src/GLFWContext.cpp.s

.PHONY : src/GLFWContext.s

# target to generate assembly for a file
src/GLFWContext.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/GLFWContext.cpp.s
.PHONY : src/GLFWContext.cpp.s

src/Object3D.o: src/Object3D.cpp.o

.PHONY : src/Object3D.o

# target to build an object file
src/Object3D.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Object3D.cpp.o
.PHONY : src/Object3D.cpp.o

src/Object3D.i: src/Object3D.cpp.i

.PHONY : src/Object3D.i

# target to preprocess a source file
src/Object3D.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Object3D.cpp.i
.PHONY : src/Object3D.cpp.i

src/Object3D.s: src/Object3D.cpp.s

.PHONY : src/Object3D.s

# target to generate assembly for a file
src/Object3D.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Object3D.cpp.s
.PHONY : src/Object3D.cpp.s

src/ObjectConnection.o: src/ObjectConnection.cpp.o

.PHONY : src/ObjectConnection.o

# target to build an object file
src/ObjectConnection.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/ObjectConnection.cpp.o
.PHONY : src/ObjectConnection.cpp.o

src/ObjectConnection.i: src/ObjectConnection.cpp.i

.PHONY : src/ObjectConnection.i

# target to preprocess a source file
src/ObjectConnection.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/ObjectConnection.cpp.i
.PHONY : src/ObjectConnection.cpp.i

src/ObjectConnection.s: src/ObjectConnection.cpp.s

.PHONY : src/ObjectConnection.s

# target to generate assembly for a file
src/ObjectConnection.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/ObjectConnection.cpp.s
.PHONY : src/ObjectConnection.cpp.s

src/Objloader.o: src/Objloader.cpp.o

.PHONY : src/Objloader.o

# target to build an object file
src/Objloader.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Objloader.cpp.o
.PHONY : src/Objloader.cpp.o

src/Objloader.i: src/Objloader.cpp.i

.PHONY : src/Objloader.i

# target to preprocess a source file
src/Objloader.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Objloader.cpp.i
.PHONY : src/Objloader.cpp.i

src/Objloader.s: src/Objloader.cpp.s

.PHONY : src/Objloader.s

# target to generate assembly for a file
src/Objloader.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Objloader.cpp.s
.PHONY : src/Objloader.cpp.s

src/OpenHmdWrapper.o: src/OpenHmdWrapper.cpp.o

.PHONY : src/OpenHmdWrapper.o

# target to build an object file
src/OpenHmdWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/OpenHmdWrapper.cpp.o
.PHONY : src/OpenHmdWrapper.cpp.o

src/OpenHmdWrapper.i: src/OpenHmdWrapper.cpp.i

.PHONY : src/OpenHmdWrapper.i

# target to preprocess a source file
src/OpenHmdWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/OpenHmdWrapper.cpp.i
.PHONY : src/OpenHmdWrapper.cpp.i

src/OpenHmdWrapper.s: src/OpenHmdWrapper.cpp.s

.PHONY : src/OpenHmdWrapper.s

# target to generate assembly for a file
src/OpenHmdWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/OpenHmdWrapper.cpp.s
.PHONY : src/OpenHmdWrapper.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Side.o: src/Side.cpp.o

.PHONY : src/Side.o

# target to build an object file
src/Side.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Side.cpp.o
.PHONY : src/Side.cpp.o

src/Side.i: src/Side.cpp.i

.PHONY : src/Side.i

# target to preprocess a source file
src/Side.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Side.cpp.i
.PHONY : src/Side.cpp.i

src/Side.s: src/Side.cpp.s

.PHONY : src/Side.s

# target to generate assembly for a file
src/Side.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Side.cpp.s
.PHONY : src/Side.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/TextureStreamSurface.o: src/TextureStreamSurface.cpp.o

.PHONY : src/TextureStreamSurface.o

# target to build an object file
src/TextureStreamSurface.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/TextureStreamSurface.cpp.o
.PHONY : src/TextureStreamSurface.cpp.o

src/TextureStreamSurface.i: src/TextureStreamSurface.cpp.i

.PHONY : src/TextureStreamSurface.i

# target to preprocess a source file
src/TextureStreamSurface.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/TextureStreamSurface.cpp.i
.PHONY : src/TextureStreamSurface.cpp.i

src/TextureStreamSurface.s: src/TextureStreamSurface.cpp.s

.PHONY : src/TextureStreamSurface.s

# target to generate assembly for a file
src/TextureStreamSurface.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/TextureStreamSurface.cpp.s
.PHONY : src/TextureStreamSurface.cpp.s

src/Vboindexer.o: src/Vboindexer.cpp.o

.PHONY : src/Vboindexer.o

# target to build an object file
src/Vboindexer.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Vboindexer.cpp.o
.PHONY : src/Vboindexer.cpp.o

src/Vboindexer.i: src/Vboindexer.cpp.i

.PHONY : src/Vboindexer.i

# target to preprocess a source file
src/Vboindexer.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Vboindexer.cpp.i
.PHONY : src/Vboindexer.cpp.i

src/Vboindexer.s: src/Vboindexer.cpp.s

.PHONY : src/Vboindexer.s

# target to generate assembly for a file
src/Vboindexer.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/Vboindexer.cpp.s
.PHONY : src/Vboindexer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/openglexample.dir/build.make CMakeFiles/openglexample.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... openglexample"
	@echo "... src/Debug.o"
	@echo "... src/Debug.i"
	@echo "... src/Debug.s"
	@echo "... src/GLFWContext.o"
	@echo "... src/GLFWContext.i"
	@echo "... src/GLFWContext.s"
	@echo "... src/Object3D.o"
	@echo "... src/Object3D.i"
	@echo "... src/Object3D.s"
	@echo "... src/ObjectConnection.o"
	@echo "... src/ObjectConnection.i"
	@echo "... src/ObjectConnection.s"
	@echo "... src/Objloader.o"
	@echo "... src/Objloader.i"
	@echo "... src/Objloader.s"
	@echo "... src/OpenHmdWrapper.o"
	@echo "... src/OpenHmdWrapper.i"
	@echo "... src/OpenHmdWrapper.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Side.o"
	@echo "... src/Side.i"
	@echo "... src/Side.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/TextureStreamSurface.o"
	@echo "... src/TextureStreamSurface.i"
	@echo "... src/TextureStreamSurface.s"
	@echo "... src/Vboindexer.o"
	@echo "... src/Vboindexer.i"
	@echo "... src/Vboindexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

